### ISSUE TITLE
[BUG] unreachable code?

### ISSUE THREAD

**Issue by chris-ha458** [nickspring/charset-normalizer-rs#12]
**Describe the bug**
[This part of the code seems to be unreachable](https://github.com/nickspring/charset-normalizer-rs/blob/801dcdd266847babde97ca3ea333ce0b77efef7f/src/entity.rs#L130)

The outer `if` ensures that `cohrerence_difference` is not 0.0.
So that particular if statement should never be reached.

**To Reproduce**
I don't know the intended case for these statements so I cannot reproduce the "negative case"

**Expected behavior**
maybe the outer if needs to be different.
In the [original python](https://github.com/Ousret/charset_normalizer/blob/58f69f76983fc2042b4f47037c02d2d74ecec2cc/charset_normalizer/models.py#L58C16-L58C78) code, `chaos_difference == 0.0 and self.coherence == other.coherence` this comparison is used.

**Comment by chris-ha458** [comment]
semantically, it seems that both code is identical so I made an issue there as well.
https://github.com/Ousret/charset_normalizer/issues/350

**Comment by nickspring** [comment]
I guess it can be removed :)

**Comment by chris-ha458** [comment]
I will wait for the original repo to respond before doing anything. I might missing something.

That being said the code can be simplified quite a bit if we can remove one predicate or the whole if statement.

**Comment by nickspring** [comment]
It was confirmed in original repo that's dead code.
